### ISSUE TITLE
readme.md modification is unintuitive

### ISSUE THREAD

**Issue by NaridaL** [nfroidure/metapak#13]
Having to edit `.readme/contents.md` instead of the readme itself is unintuitive, I'd suggest the following alternative:

Have the header/footer marked by comments inside README.md, e.g.

```
<!-- METAPAK-HEADER-START -->
autogen content
<!-- METAPAK-HEADER-END -->
manually edited content
<!-- METAPAK-FOOTER-START -->
autogen content
<!-- METAPAK-FOOTER-END -->
```

then this package can find where the header/footer starts/ends and edit the readme in-place.

**Comment by nfroidure** [comment]
Hi @NaridaL !

That's just the way I'm doing it in `metapak-nfroidure` https://github.com/nfroidure/metapak-nfroidure/tree/master/src/readme

You can simply remove README templating by removing "readme" from the plugins list in your `package.json` like here https://github.com/nfroidure/metapak-nfroidure/blob/master/package.json#L7

That said I agree it would be better, I often find myself erasing some README.md edited contents... So i created an issue to handle that https://github.com/nfroidure/metapak-nfroidure/issues/10

No idea when I'll find time to do it though.
